server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  rabbitmq:
    host: 192.168.219.101
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
#        - id: users-service
#          # eureka에 등록된 application명으로 작성
#          uri: lb://USERS-SERVICE
#          # 해당 Path를 적용시키기 위해선 마이크로서비스의 controller의 requestmapping의 baseurl이 일치해야함
#          predicates:
#            - Path=/users-service/**
        # 로그인
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            # 해당 path로 들어오면 해당 서비스로 간 다음에 콤마(,) 뒤의 패턴으로 변경해서 요청
            # 해당 서비스의 RequestMapping에서 xxx-service라고 등록할 필요 없음
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        # 회원가입
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        # 일반
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        # user-service의 actuator를 위한 등록
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}

        - id: catalogs-service
          uri: lb://CATALOGS-SERVICE
          predicates:
            - Path=/catalogs-service/**

        - id: orders-service
          uri: lb://ORDERS-SERVICE
          predicates:
            - Path=/orders-service/**

management:
  endpoints:
    web:
      exposure:
        # httptrace를 사용하기 위해서는 application에 bean을 하나 등록시켜줘야 함
        include: refresh, health, beans, httptrace, busrefresh

# Jwt
#token:
#  secret: my_jwt_token