server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # file:\\\C:\Users\SIWON\Desktop\SSAFY\98_Spring-Cloud-Config
          uri: file:///Users/SIWON/Desktop/SSAFY/98_Spring-Cloud-Config
